dataset:
  root: /kaggle/input/datasets/ahmedmohamed365/volleyball/volleyball_/videos/
  annot_file: /kaggle/input/datasets/tareksaber/annot-all-pkl/annot_all.pkl


  splits:
    train: ["1", "3", "6", "7", "10", "13", "15", "16", "18", "22", "23", "31","32", "36", "38", "39", "40", "41", "42", "48", "50", "52", "53", "54"]
    val: ["0", "2", "8", "12", "17", "19", "24", "26", "27", "28", "30", "33", "46", "49", "51"]
    test: ['4','5','9','11','14','20','21','25','29','34','35','37','43','44','45','47']

  classes:
    waiting: 0
    setting: 1
    digging: 2 
    falling: 3
    spiking: 4
    blocking: 5
    jumping: 6
    moving: 7 
    standing: 8
  


train:
  optimizer:
    type: adamw
    lr: 0.0001
    weight_decay: 1e-1

  epochs: 20

  scheduler:
    type: reduce_on_plateau
    patience : 3
    factor : 0.1

  batch_size:
    train : 4
    val : 4

  num_workers : 4
  pin_memory : True

  backbone: /kaggle/input/models/tareksaber/b3-player-classifier-model/pytorch/default/1/checkpoint.pth

experiment:
  output_dir: /kaggle/working/b5/playerclassifier
  name: model_1_config_1